package com.app.phoneticalphabet.models

data class Word(
    val letter: String,
    val word: String
) {
    companion object {
        val alphabet = listOf(
            Word("A", "Alpha"),
            Word("B", "Bravo"),
            Word("C", "Charlie"),
            Word("D", "Delta"),
            Word("E", "Echo"),
            Word("F", "Foxtrot"),
            Word("G", "Golf"),
            Word("H", "Hotel"),
            Word("I", "India"),
            Word("J", "Juliett"),
            Word("K", "Kilo"),
            Word("L", "Lima"),
            Word("M", "Mike"),
            Word("N", "November"),
            Word("O", "Oscar"),
            Word("P", "Papa"),
            Word("Q", "Quebec"),
            Word("R", "Romeo"),
            Word("S", "Sierra"),
            Word("T", "Tango"),
            Word("U", "Uniform"),
            Word("V", "Victor"),
            Word("W", "Whiskey"),
            Word("X", "X-ray"),
            Word("Y", "Yankee"),
            Word("Z", "Zulu")
        )

        val wrongWords: List<String> =
            listOf(
                "Area",
                "Air",
                "Apple",
                "Beta",
                "Blast",
                "Bomb",
                "Charles",
                "Connor",
                "Cameron",
                "Dynamic",
                "Duty",
                "Dust",
                "Eagle",
                "Easy",
                "Eat",
                "False",
                "Flow",
                "Fresh",
                "Gun",
                "Gulf",
                "Gold",
                "Hurt",
                "Hope",
                "Hero",
                "Island",
                "Italy",
                "Ireland",
                "Julia",
                "James",
                "Justin",
                "Kangaroo",
                "Kid",
                "Kitty",
                "Law",
                "Love",
                "Lock",
                "Monday",
                "Money",
                "Military",
                "Nail",
                "Neck",
                "Night",
                "Olive",
                "Ocean",
                "October",
                "Puma",
                "Peach",
                "Plane",
                "Quack",
                "Qatar",
                "Quail",
                "Roma",
                "Rise",
                "Right",
                "Spain",
                "Steam",
                "Straight",
                "True",
                "Turkey",
                "Texas",
                "Ugly",
                "Ultra",
                "Uber",
                "Victoria",
                "Violet",
                "Valentino",
                "William",
                "Wade",
                "World",
                "Xander",
                "X-gun",
                "X-light",
                "Yasmin",
                "Yoga",
                "Young",
                "Zion",
                "Zane",
                "Zimbabwe"
            )
    }
}