package com.app.phoneticalphabet.models

data class Word(
    val letter: String,
    val word: String
) {
    companion object {
        val alphabet = listOf(
            Word("A", "alpha"),
            Word("B", "bravo"),
            Word("C", "charlie"),
            Word("D", "delta"),
            Word("E", "echo"),
            Word("F", "foxtrot"),
            Word("G", "golf"),
            Word("H", "hotel"),
            Word("I", "india"),
            Word("J", "juliett"),
            Word("K", "kilo"),
            Word("L", "lima"),
            Word("M", "mike"),
            Word("N", "november"),
            Word("O", "oscar"),
            Word("P", "papa"),
            Word("Q", "quebec"),
            Word("R", "romeo"),
            Word("S", "sierra"),
            Word("T", "tango"),
            Word("U", "uniform"),
            Word("V", "victor"),
            Word("W", "whiskey"),
            Word("X", "x-ray"),
            Word("Y", "yankee"),
            Word("Z", "zulu")
        )

        val wrongWords: List<String> =
            listOf(
                "Area",
                "Air",
                "Apple",
                "Beta",
                "Blast",
                "Bomb",
                "Charles",
                "Connor",
                "Cameron",
                "Dynamic",
                "Duty",
                "Dust",
                "Eagle",
                "Easy",
                "Eat",
                "False",
                "Flow",
                "Fresh",
                "Gun",
                "Gulf",
                "Gold",
                "Hurt",
                "Hope",
                "Hero",
                "Island",
                "Italy",
                "Ireland",
                "Julia",
                "James",
                "Justin",
                "Kangaroo",
                "Kid",
                "Kitty",
                "Law",
                "Love",
                "Lock",
                "Monday",
                "Money",
                "Military",
                "Nail",
                "Neck",
                "Night",
                "Olive",
                "Ocean",
                "October",
                "Puma",
                "Peach",
                "Plane",
                "Quack",
                "Qatar",
                "Quail",
                "Roma",
                "Rise",
                "Right",
                "Spain",
                "Steam",
                "Straight",
                "True",
                "Turkey",
                "Texas",
                "Ugly",
                "Ultra",
                "Uber",
                "Victoria",
                "Violet",
                "Valentino",
                "William",
                "Wade",
                "World",
                "Xander",
                "X-gun",
                "X-light",
                "Yasmin",
                "Yoga",
                "Young",
                "Zion",
                "Zane",
                "Zimbabwe"
            )
    }
}